export const data = [
  {
    name: "Raghuvendra Raga",
    assets: {
      total: "$35342",
      gold: "50.54g",
      silver: "34.2g",
      other: "24.2g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "9876543210@trucard",
  },
  {
    name: "Abhinav Loyal",
    assets: {
      total: "₹35,342",
      gold: "34.2g",
      silver: "242.5g",
      other: "242.5",
    },
    revenue: "35,342",
    kyc: "Pending",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Singh",
    },
    zone: "South",
    accType: "Pay and Use(Minor)",
    tpa: "9876543210@trucard",
  },
  {
    name: "Raghuvendra Raga",
    assets: {
      total: "$35342",
      gold: "50.54g",
      silver: "34.2g",
      other: "242.5g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "",
    tpa: "9876543210@trucard",
  },
  {
    name: "Abhinav Loyal",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "123456874@trucard",
  },
  {
    name: "Ashis Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "8524@trucard",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "7688585@trucarrdggad",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "8588@fag",
  },
  {
    name: "Raju Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Pending",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "7575757@eFWERWW",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "54ergk@sf",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "52s44@sss",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "safd@asdf",
  },
  {
    name: "Raghubendra Raja",
    assets: {
      total: "$35342",
      gold: "30g",
      silver: "20.5g",
      other: "10.4g",
    },
    revenue: "35,342",
    kyc: "Done",
    Facilitator: {
      from: "Arun Jha",
      to: "Anika Sing",
    },
    zone: "South",
    accType: "Bussiness",
    tpa: "5192@wsdf",
  },
];
